name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz openjdk-17-jdk  # Для PlantUML
          
      - name: Download PlantUML
        run: |
          mkdir -p plantuml
          wget -O plantuml/plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2025.0/plantuml-1.2025.0.jar
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          sed -i '/pywin32/d' requirements.txt  # Удаляем pywin32 из списка зависимостей
          pip install -r requirements.txt

      - name: Build Sphinx site
        run: |
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build/html
          force_orphan: true  # Очищает историю ветки gh-pages
